export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FILTER_PRODUCT_BY_CATEGORY = 'FILTER_PRODUCT_BY_CATEGORY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const POST_ORDER = 'POST_ORDER';
